name = "notepad-app"
type = "javascript"

account_id = "a681f451b8fcc1d50f7b8b5870b891d2"
workers_dev = true
compatibility_date = "2023-06-01"

[vars]
MONGO_URI = "mongodb+srv://NewPomPom:NewPomPom@cluster0.dyu5iru.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
LOGIN_USERNAME = "DeadUserXYZ"
LOGIN_PASSWORD = "Sahil31"
